/**
 * Textos del catalogo de proyectos.
 *
 * Los filtros se construyen a partir de datos reales de `projects.ts`: zona,
 * habitaciones y amenidades. No hay categorias inventadas ni etiquetas
 * comerciales que el material no respalde.
 */
export const catalogCopy = {
  es: {
    eyebrow: "Catálogo",
    title: ["Tres lugares.", "Un mismo acompañamiento."],
    intro:
      "Explora los proyectos en Punta Cana. Compara sus espacios, guarda tus favoritos y encuentra tu próximo paso.",
    filtersLabel: "Filtrar proyectos",
    zone: "Zona",
    bedrooms: "Habitaciones",
    price: "Precio",
    delivery: "Entrega",
    productType: "Tipo",
    amenities: "Amenidades",
    all: "Todos",
    results: (n: number) => (n === 1 ? "1 proyecto" : `${n} proyectos`),
    empty: "Ningún proyecto coincide con esa combinación.",
    emptyAction: "Quitar los filtros",
    clear: "Limpiar",
    open: "Ver el proyecto",
    location: "Abrir ubicación",
    pending: "Ficha en revisión",
    complete: "Ficha completa",
    bedroomsValue: (list: number[]) =>
      list.length === 0 ? "Consultar" : `${list.join(", ")} habitaciones`,
    areaValue: (min: number, max: number, unit: string) =>
      min === 0 ? "Consultar" : `${min} a ${max} ${unit}`,
    greenValue: (value: number) =>
      value === 0 ? "Consultar" : `${value.toLocaleString("es-DO")} m² verdes`,
    note: "Las imágenes son renders entregados por cada desarrollador. Precios, disponibilidad y fechas de entrega se confirman antes de cualquier reserva.",
    backHome: "Inicio",
    priceFrom: "Desde",
    pricePending: "Consultar precio",
    anyPrice: "Cualquier precio",
    upTo: (amount: string) => `Hasta ${amount}`,
    confirmedPrice: "Con precio publicado",
    pendingPrice: "Precio a consultar",
    immediateOrConstruction: "Inmediata o construcción",
    appliances: "Línea blanca incluida",
    reservation: "Reserva",
    paymentPlan: "Plan de pago",
    benefits: "Beneficios",
    nearby: "Cercanías",
    typologies: "Tipologías",
    bedroomsShort: "hab.",
    bathroomsShort: "baños",
    parkingShort: "parqueos",
    pendingShort: "Consultar",
    save: (name: string) => `Guardar ${name}`,
    unsave: (name: string) => `Quitar ${name} de guardados`,
    image: (current: number, total: number) => `Imagen ${current} de ${total}`,
    goToImage: (n: number) => `Ver la imagen ${n}`,
    // Comparador y filtros iterativos
    compare: "Comparar",
    comparing: "En comparativa",
    addToCompare: (name: string) => `Añadir ${name} al comparador`,
    removeFromCompare: (name: string) => `Quitar ${name} del comparador`,
    compareSelected: (count: number) => `Comparar (${count})`,
    compareAll: "Comparar los 3",
    compareTitle: "Comparativa de proyectos",
    compareSubtitle: "Revisa precio, entrega, ubicación, tipologías y amenidades en una sola matriz.",
    compareTrayLabel: "Abrir opciones de comparación",
    compareTrayClose: "Cerrar opciones de comparación",
    compareTrayHint: "Toca para ver acciones",
    onlyDifferences: "Solo diferencias",
    allDetails: "Todos los datos",
    closeComparison: "Cerrar comparador",
    clearComparison: "Limpiar selección",
    selectedCount: (count: number, total: number) => `${count} de ${total} seleccionados`,
    dockPrompt: "Selecciona proyectos para contrastar especificaciones lado a lado.",
    whatsappCompare: (names: string) =>
      `Hola Andris, estoy evaluando los siguientes proyectos en tu web: ${names}. Quisiera consultar disponibilidad, precios actualizados y planes de pago.`,
    contactAdvisor: "Consultar con Andris",
    filterAdvanced: "Filtros avanzados",
    activeFiltersLabel: "Filtros activos",
    clearAll: "Limpiar filtros",
    confoturTitle: "Incentivo CONFOTUR",
    confoturYes: "Exención fiscal por 15 años (IPI y transferencia)",
    confoturNo: "No aplica",
    categoryInvestment: "Inversión y Pagos",
    categorySpace: "Espacios y Metrajes",
    categoryTax: "Incentivos y Fiscalidad",
    categoryLocation: "Ubicación y Entorno",
    categoryAmenities: "Equipamiento y Amenidades",
    includedFeature: "Incluido",
    valueUnavailable: "Dato no suministrado",
    verifiedStatus: "Disponible",
    pendingStatus: "A validar",
  },
  en: {
    eyebrow: "Catalogue",
    title: ["Three places.", "The same guidance."],
    intro:
      "Explore projects in Punta Cana. Compare their spaces, save your favourites and find your next step.",
    filtersLabel: "Filter projects",
    zone: "Area",
    bedrooms: "Bedrooms",
    price: "Price",
    delivery: "Delivery",
    productType: "Type",
    amenities: "Amenities",
    all: "All",
    results: (n: number) => (n === 1 ? "1 project" : `${n} projects`),
    empty: "No project matches that combination.",
    emptyAction: "Clear the filters",
    clear: "Clear",
    open: "View the project",
    location: "Open location",
    pending: "Profile in review",
    complete: "Full profile",
    bedroomsValue: (list: number[]) =>
      list.length === 0 ? "Ask advisor" : `${list.join(", ")} bedrooms`,
    areaValue: (min: number, max: number, unit: string) =>
      min === 0 ? "Ask advisor" : `${min} to ${max} ${unit}`,
    greenValue: (value: number) =>
      value === 0 ? "Ask advisor" : `${value.toLocaleString("en-US")} m² of greenery`,
    note: "Images are renderings supplied by each developer. Prices, availability and handover dates are confirmed before any reservation.",
    backHome: "Home",
    priceFrom: "From",
    pricePending: "Ask for price",
    anyPrice: "Any price",
    upTo: (amount: string) => `Up to ${amount}`,
    confirmedPrice: "Published price",
    pendingPrice: "Ask for price",
    immediateOrConstruction: "Immediate or construction",
    appliances: "Appliances included",
    reservation: "Reservation",
    paymentPlan: "Payment plan",
    benefits: "Benefits",
    nearby: "Nearby",
    typologies: "Typologies",
    bedroomsShort: "bed",
    bathroomsShort: "bath",
    parkingShort: "parking",
    pendingShort: "Ask",
    save: (name: string) => `Save ${name}`,
    unsave: (name: string) => `Remove ${name} from saved`,
    image: (current: number, total: number) => `Image ${current} of ${total}`,
    goToImage: (n: number) => `View image ${n}`,
    // Comparison and interactive filters
    compare: "Compare",
    comparing: "Comparing",
    addToCompare: (name: string) => `Add ${name} to comparison`,
    removeFromCompare: (name: string) => `Remove ${name} from comparison`,
    compareSelected: (count: number) => `Compare (${count})`,
    compareAll: "Compare all 3",
    compareTitle: "Project Comparison",
    compareSubtitle: "Review price, delivery, location, layouts and amenities in one matrix.",
    compareTrayLabel: "Open comparison options",
    compareTrayClose: "Close comparison options",
    compareTrayHint: "Tap to show actions",
    onlyDifferences: "Only differences",
    allDetails: "All details",
    closeComparison: "Close comparison",
    clearComparison: "Clear selection",
    selectedCount: (count: number, total: number) => `${count} of ${total} selected`,
    dockPrompt: "Select projects to contrast specifications side by side.",
    whatsappCompare: (names: string) =>
      `Hello Andris, I am reviewing the following projects on your site: ${names}. I would like to check availability, updated pricing and payment terms.`,
    contactAdvisor: "Consult with Andris",
    filterAdvanced: "Advanced filters",
    activeFiltersLabel: "Active filters",
    clearAll: "Clear filters",
    confoturTitle: "CONFOTUR Tax Incentive",
    confoturYes: "15-year tax exemption (property tax and transfer tax)",
    confoturNo: "Does not apply",
    categoryInvestment: "Investment & Payment",
    categorySpace: "Spaces & Dimensions",
    categoryTax: "Tax & Incentives",
    categoryLocation: "Location & Surroundings",
    categoryAmenities: "Amenities & Equipment",
    includedFeature: "Included",
    valueUnavailable: "Data not supplied",
    verifiedStatus: "Available",
    pendingStatus: "To review",
  },
  fr: {
    eyebrow: "Catalogue",
    title: ["Trois lieux.", "Un même accompagnement."],
    intro:
      "Explorez les projets à Punta Cana. Comparez les espaces, enregistrez vos favoris et préparez la prochaine étape.",
    filtersLabel: "Filtrer les projets",
    zone: "Zone",
    bedrooms: "Chambres",
    price: "Prix",
    delivery: "Livraison",
    productType: "Type",
    amenities: "Prestations",
    all: "Tous",
    results: (n: number) => (n === 1 ? "1 projet" : `${n} projets`),
    empty: "Aucun projet ne correspond à cette combinaison.",
    emptyAction: "Retirer les filtres",
    clear: "Effacer",
    open: "Voir le projet",
    location: "Ouvrir la localisation",
    pending: "Fiche en révision",
    complete: "Fiche complète",
    bedroomsValue: (list: number[]) =>
      list.length === 0 ? "Consulter" : `${list.join(", ")} chambres`,
    areaValue: (min: number, max: number, unit: string) =>
      min === 0 ? "Consulter" : `${min} à ${max} ${unit}`,
    greenValue: (value: number) =>
      value === 0 ? "Consulter" : `${value.toLocaleString("fr-FR")} m² de verdure`,
    note: "Les images sont des perspectives fournies par chaque promoteur. Prix, disponibilité et dates de livraison sont confirmés avant toute réservation.",
    backHome: "Accueil",
    priceFrom: "À partir de",
    pricePending: "Consulter le prix",
    anyPrice: "Tous les prix",
    upTo: (amount: string) => `Jusqu'à ${amount}`,
    confirmedPrice: "Prix publié",
    pendingPrice: "Prix à consulter",
    immediateOrConstruction: "Immédiate ou construction",
    appliances: "Électroménagers inclus",
    reservation: "Réservation",
    paymentPlan: "Plan de paiement",
    benefits: "Avantages",
    nearby: "À proximité",
    typologies: "Typologies",
    bedroomsShort: "ch.",
    bathroomsShort: "sdb",
    parkingShort: "parking",
    pendingShort: "Consulter",
    save: (name: string) => `Enregistrer ${name}`,
    unsave: (name: string) => `Retirer ${name} des favoris`,
    image: (current: number, total: number) => `Image ${current} sur ${total}`,
    goToImage: (n: number) => `Voir l'image ${n}`,
    // Comparateur et filtres interactifs
    compare: "Comparer",
    comparing: "En comparaison",
    addToCompare: (name: string) => `Ajouter ${name} au comparateur`,
    removeFromCompare: (name: string) => `Retirer ${name} du comparateur`,
    compareSelected: (count: number) => `Comparer (${count})`,
    compareAll: "Comparer les 3",
    compareTitle: "Comparatif des Projets",
    compareSubtitle: "Comparez prix, livraison, localisation, typologies et prestations dans une seule matrice.",
    compareTrayLabel: "Ouvrir les options de comparaison",
    compareTrayClose: "Fermer les options de comparaison",
    compareTrayHint: "Touchez pour voir les actions",
    onlyDifferences: "Uniquement les différences",
    allDetails: "Toutes les données",
    closeComparison: "Fermer le comparateur",
    clearComparison: "Effacer la sélection",
    selectedCount: (count: number, total: number) => `${count} sur ${total} sélectionnés`,
    dockPrompt: "Sélectionnez des projets pour comparer leurs spécifications côte à côte.",
    whatsappCompare: (names: string) =>
      `Bonjour Andris, j'évalue actuellement les projets suivants sur votre site : ${names}. J'aimerais vérifier la disponibilité, les prix actualisés et les conditions de paiement.`,
    contactAdvisor: "Consulter Andris",
    filterAdvanced: "Filtres avancés",
    activeFiltersLabel: "Filtres actifs",
    clearAll: "Effacer les filtres",
    confoturTitle: "Incitation fiscale CONFOTUR",
    confoturYes: "Exonération fiscale pendant 15 ans (IPI et droits de mutation)",
    confoturNo: "Non applicable",
    categoryInvestment: "Investissement & Paiement",
    categorySpace: "Espaces & Dimensions",
    categoryTax: "Fiscalité & Incitations",
    categoryLocation: "Localisation & Cadre",
    categoryAmenities: "Équipements & Prestations",
    includedFeature: "Inclus",
    valueUnavailable: "Donnée non fournie",
    verifiedStatus: "Disponible",
    pendingStatus: "À valider",
  },
} as const;
