import type { Locale } from "./projects";
const es = {
  role: "Asesor inmobiliario",
  location: "Punta Cana, República Dominicana",
  portfolio: "Portafolio inmobiliario",
  nav: ["Inicio", "Proyectos", "Sobre mí", "Tu inversión", "Conversemos"],
  tagline: "Tu próximo capítulo,",
  taglineItalic: "en el lugar correcto.",
  heroKicker: "PERSONAS. LUGARES. NUEVOS COMIENZOS.",
  heroLeft: "Un lugar para vivir.\nUna decisión para crecer.",
  heroRight:
    "Te acompaño a descubrir una propiedad que conecte con lo que quieres para tu futuro.",
  explore: "Explorar proyectos",
  meet: "Conoce a Andris",
  scroll: "Desliza para descubrir",
  personal: "Asesoría personal",
  sidebarText: "Las grandes decisiones empiezan con una buena conversación.",
  talk: "Conversemos",
  selection: "01 / ESPACIOS CON PROPÓSITO",
  projectsTitle: "Imagina tu vida",
  projectsItalic: "aquí.",
  projectsIntro:
    "Una mirada más cercana a los espacios, los detalles y las posibilidades de tu próximo hogar.",
  featured: "PROYECTO DESTACADO",
  viewProject: "Descubrir el proyecto",
  renders: "Renders del proyecto · Imágenes ilustrativas",
  bedrooms: "Habitaciones",
  area: "Superficie",
  green: "Áreas verdes",
  detail: "Los detalles hacen la diferencia.",
  gallery: "Explorar galería",
  galleryTitle: "Un vistazo a tu próximo espacio.",
  allPhotos: "Ver todas las imágenes",
  facets: [
    "Naturaleza que se vive",
    "Tiempo para ti",
    "Espacios para compartir",
  ],
  facetTags: ["SUMMER GARDENS", "VIDA TIPO RESORT", "INTERIORES"],
  amenities: "Todo lo que hace hogar",
  consultAvailability: "Consultar disponibilidad",
  availabilityNote:
    "Precio, disponibilidad, condiciones y entrega sujetos a confirmación.",
  mapLabel: "EL LUGAR IMPORTA",
  mapTitle: "Tu punto de partida,",
  mapItalic: "Vista Cana.",
  mapDescription:
    "Un entorno residencial en Punta Cana, con lagos, senderos ecológicos, golf y espacios para disfrutar al aire libre.",
  openMap: "Abrir ubicación",
  loadMap: "Explorar mapa interactivo",
  mapPrivacy: "Al abrir el mapa se conecta con OpenStreetMap.",
  mapUnavailable:
    "El mapa no está disponible sin conexión. Puedes guardar la ubicación y abrirla más tarde.",
  mapPin: "Ubicación del proyecto",
  aboutLabel: "02 / DETRÁS DE CADA DECISIÓN",
  aboutTitle: "Mucho más que una propiedad.",
  aboutItalic: "Tu próximo capítulo.",
  aboutText:
    "Soy Andris Peña, asesor inmobiliario. Este espacio es una invitación a explorar proyectos en Punta Cana y a conversar sobre lo que buscas, con información clara y atención personal.",
  aboutQuote:
    "Primero, lo que importa para ti. Después, el lugar que lo hace posible.",
  aboutCTA: "Hablemos de tus planes",
  processLabel: "UN CAMINO, CONTIGO",
  processTitle: "Del «me lo imagino»",
  processItalic: "al siguiente paso.",
  steps: [
    {
      title: "Te escucho",
      text: "¿Un hogar, una segunda residencia o una inversión? Empezamos por tus prioridades.",
    },
    {
      title: "Exploramos",
      text: "Conocemos el proyecto, sus espacios y la información que necesitas para comparar.",
    },
    {
      title: "Hacemos números",
      text: "Organizamos un escenario de pagos y las preguntas que conviene aclarar.",
    },
    {
      title: "Damos el siguiente paso",
      text: "Preparamos tu consulta para confirmar disponibilidad, condiciones y una posible visita.",
    },
  ],
  calcLabel: "03 / DALE FORMA A TUS PLANES",
  calcTitle: "Tu inversión,",
  calcItalic: "paso a paso.",
  calcIntro:
    "Visualiza cómo se distribuirían tus pagos. Ajusta los números a tu propio escenario.",
  calcBadge: "SIMULADOR DE PAGOS",
  propertyValue: "Valor de la propiedad",
  currency: "Dólares estadounidenses (USD)",
  months: "Meses de construcción",
  signing: "A la firma",
  construction: "Durante construcción",
  delivery: "A la entrega",
  monthly: "Cuota mensual estimada",
  monthsUnit: "meses",
  calcNote:
    "Ejercicio ilustrativo, no una oferta ni un cálculo hipotecario. La reserva, gastos, impuestos y financiamiento no están incluidos. El plan 10 / 40 / 50 del material recibido requiere confirmar vigencia y cómo se aplica la reserva.",
  calcError:
    "Introduce un valor mayor que 0, entre 1 y 120 meses y porcentajes que no superen 100%.",
  lastPayment: "Última cuota ajustada por redondeo",
  reset: "Restablecer",
  downloadPlan: "Descargar mi escenario",
  guideLabel: "DECIDIR CON INFORMACIÓN",
  guideTitle: "Buenas preguntas.",
  guideItalic: "Mejores decisiones.",
  faqs: [
    {
      q: "¿Por dónde empiezo si quiero invertir?",
      a: "Define el uso que buscas para la propiedad, tu presupuesto total y el plazo. Después reúne la ficha del proyecto, las condiciones de pago y las preguntas que quieres resolver con el asesor.",
    },
    {
      q: "¿Qué significa un plan de pagos 10 / 40 / 50?",
      a: "Es una distribución del valor: 10% a la firma, 40% durante la construcción y 50% a la entrega. Las fechas, cuotas y aplicación de la reserva deben confirmarse en la oferta y en el contrato de cada unidad.",
    },
    {
      q: "¿Qué debo confirmar antes de reservar?",
      a: "La disponibilidad de la unidad, precio vigente, ubicación, fecha de entrega, especificaciones, gastos adicionales y condiciones de devolución. Solicita la documentación del proyecto y revísala con profesionales independientes.",
    },
    {
      q: "¿Puedo preparar mi compra desde el extranjero?",
      a: "Puedes empezar organizando tus objetivos y revisando el material del proyecto a distancia. Consulta qué documentos, verificaciones y pasos presenciales o mediante representación requiere tu caso.",
    },
  ],
  contactLabel: "EL SIGUIENTE CAPÍTULO EMPIEZA AQUÍ",
  contactTitle: "Cuéntame qué",
  contactItalic: "tienes en mente.",
  contactIntro:
    "Un hogar para ti. Un espacio para desconectar. Un proyecto para el futuro. Empecemos por tu idea.",
  name: "Tu nombre",
  namePlaceholder: "¿Cómo te llamas?",
  email: "Correo electrónico",
  emailPlaceholder: "tu@correo.com",
  interest: "Me interesa",
  interests: [
    "Conocer Melcon Paradise",
    "Mi primera propiedad",
    "Una segunda residencia",
    "Explorar una inversión",
  ],
  message: "Cuéntame un poco más",
  messagePlaceholder: "Qué buscas, tu plazo, tus preguntas…",
  consent:
    "Entiendo que se preparará un resumen de mi consulta en este dispositivo.",
  prepare: "Preparar mi consulta",
  prepared: "Tu consulta está preparada",
  preparedText: "Descarga o copia tu resumen. Aún no se ha enviado a Andris.",
  noContact:
    "El canal de contacto directo estará disponible cuando se confirme su información oficial.",
  copy: "Copiar consulta",
  copied: "Copiado",
  download: "Descargar consulta",
  sendEmail: "Continuar por correo",
  sendWhatsApp: "Continuar por WhatsApp",
  privacy: "Privacidad",
  privacyText:
    "Tus datos se usan solo para preparar esta consulta en tu navegador. No se envían ni se guardan en un servidor. Al continuar por correo o WhatsApp se abrirá el servicio elegido y podrás revisar el mensaje antes de enviarlo. El mapa se conecta con OpenStreetMap solo al abrirlo. La app guarda en este dispositivo idioma, apariencia y favoritos; puedes restablecerlos desde Ajustes.",
  independent: "Portafolio independiente de Andris Peña.",
  footerNote: "Cada gran historia empieza con un lugar.",
  rights: "Todos los derechos reservados.",
  settings: "Ajustes",
  appearance: "Apariencia",
  light: "Claro",
  dark: "Oscuro",
  system: "Sistema",
  language: "Idioma",
  install: "Instalar aplicación",
  installText: "Lleva tus próximos planes contigo.",
  installHelp:
    "En iPhone: Compartir → Añadir a pantalla de inicio. En otros navegadores: abre el menú y busca Instalar aplicación. Requiere HTTPS o localhost.",
  installed: "La aplicación ya está instalada.",
  offline:
    "Estás sin conexión. El contenido guardado sigue disponible; mapa y contacto necesitan internet.",
  clearPreferences: "Restablecer preferencias",
  close: "Cerrar",
  back: "Volver",
  previous: "Imagen anterior",
  next: "Imagen siguiente",
  saved: "Proyecto guardado",
  save: "Guardar proyecto",
  removeSaved: "Quitar de guardados",
  savedEmpty: "Todavía no has guardado proyectos.",
  favorites: "Guardados",
  skip: "Saltar al contenido",
  notFound: "Este lugar aún no está aquí.",
  notFoundText: "Vuelve al portafolio para explorar el proyecto disponible.",
  home: "Volver al inicio",
  themeToggle: "Cambiar apariencia",
  share: "Compartir proyecto",
  shared: "Enlace copiado",
  preparing: "Preparando",
  noPhoto: "No se pudo cargar esta imagen.",
  retry: "Reintentar",
  view: "Ver proyecto",
};
type Copy = typeof es;
const en: Copy = {
  role: "Real estate advisor",
  location: "Punta Cana, Dominican Republic",
  portfolio: "Real estate portfolio",
  nav: ["Home", "Projects", "About me", "Your investment", "Let’s talk"],
  tagline: "Your next chapter,",
  taglineItalic: "in the right place.",
  heroKicker: "PEOPLE. PLACES. NEW BEGINNINGS.",
  heroLeft: "A place to live.\nA decision to grow.",
  heroRight:
    "I help you discover a property that connects with what you want for your future.",
  explore: "Explore projects",
  meet: "Meet Andris",
  scroll: "Scroll to discover",
  personal: "Personal guidance",
  sidebarText: "Great decisions begin with a good conversation.",
  talk: "Let’s talk",
  selection: "01 / SPACES WITH PURPOSE",
  projectsTitle: "Imagine your life",
  projectsItalic: "here.",
  projectsIntro:
    "A closer look at the spaces, the details and the possibilities of your next home.",
  featured: "FEATURED PROJECT",
  viewProject: "Discover the project",
  renders: "Project renderings · Illustrative images",
  bedrooms: "Bedrooms",
  area: "Area",
  green: "Green spaces",
  detail: "The details make the difference.",
  gallery: "Explore gallery",
  galleryTitle: "A glimpse of your next space.",
  allPhotos: "View all images",
  facets: ["Nature, lived every day", "Time for yourself", "Spaces to share"],
  facetTags: ["SUMMER GARDENS", "RESORT LIVING", "INTERIORS"],
  amenities: "Everything that makes a home",
  consultAvailability: "Check availability",
  availabilityNote:
    "Price, availability, terms and delivery require confirmation.",
  mapLabel: "LOCATION MATTERS",
  mapTitle: "Your starting point,",
  mapItalic: "Vista Cana.",
  mapDescription:
    "A residential setting in Punta Cana with lakes, nature trails, golf and spaces to enjoy the outdoors.",
  openMap: "Open location",
  loadMap: "Explore interactive map",
  mapPrivacy: "Opening the map connects to OpenStreetMap.",
  mapUnavailable:
    "The map is unavailable offline. Save the location to open it later.",
  mapPin: "Project location",
  aboutLabel: "02 / BEHIND EVERY DECISION",
  aboutTitle: "More than a property.",
  aboutItalic: "Your next chapter.",
  aboutText:
    "I’m Andris Peña, a real estate advisor. This space is an invitation to explore projects in Punta Cana and talk about what you are looking for, with clear information and personal attention.",
  aboutQuote:
    "First, what matters to you. Then, the place that makes it possible.",
  aboutCTA: "Let’s talk about your plans",
  processLabel: "A PATH, TOGETHER",
  processTitle: "From “I can picture it”",
  processItalic: "to your next step.",
  steps: [
    {
      title: "I listen",
      text: "A home, a second residence or an investment? We start with your priorities.",
    },
    {
      title: "We explore",
      text: "Get to know the project, its spaces and the information you need to compare.",
    },
    {
      title: "We do the numbers",
      text: "Build a payment scenario and organize the questions worth asking.",
    },
    {
      title: "We take the next step",
      text: "Prepare your inquiry to confirm availability, terms and a possible visit.",
    },
  ],
  calcLabel: "03 / GIVE YOUR PLANS SHAPE",
  calcTitle: "Your investment,",
  calcItalic: "step by step.",
  calcIntro:
    "See how your payments could be distributed. Adjust the numbers to your own scenario.",
  calcBadge: "PAYMENT SIMULATOR",
  propertyValue: "Property value",
  currency: "US dollars (USD)",
  months: "Construction months",
  signing: "At signing",
  construction: "During construction",
  delivery: "On delivery",
  monthly: "Estimated monthly payment",
  monthsUnit: "months",
  calcNote:
    "An illustrative exercise, not an offer or mortgage calculation. Reservation, fees, taxes and financing are not included. The supplied 10 / 40 / 50 plan requires confirmation, including how the reservation is applied.",
  calcError:
    "Enter a value above 0, between 1 and 120 months and percentages totaling no more than 100%.",
  lastPayment: "Final payment adjusted for rounding",
  reset: "Reset",
  downloadPlan: "Download my scenario",
  guideLabel: "INFORMED DECISIONS",
  guideTitle: "Good questions.",
  guideItalic: "Better decisions.",
  faqs: [
    {
      q: "Where do I start if I want to invest?",
      a: "Define your intended use, total budget and timeframe. Then gather the project details, payment terms and the questions you want to discuss with your advisor.",
    },
    {
      q: "What does a 10 / 40 / 50 payment plan mean?",
      a: "It distributes the property value: 10% at signing, 40% during construction and 50% on delivery. Dates, installments and the application of the reservation must be confirmed in the offer and contract for each unit.",
    },
    {
      q: "What should I confirm before reserving?",
      a: "Unit availability, current price, location, delivery date, specifications, additional costs and refund terms. Request the project documentation and review it with independent professionals.",
    },
    {
      q: "Can I prepare a purchase from abroad?",
      a: "You can begin by organizing your goals and reviewing project materials remotely. Ask which documents, checks and in-person or representative steps your case requires.",
    },
  ],
  contactLabel: "YOUR NEXT CHAPTER STARTS HERE",
  contactTitle: "Tell me what",
  contactItalic: "you have in mind.",
  contactIntro:
    "A home for you. A place to unwind. A project for the future. Let’s start with your idea.",
  name: "Your name",
  namePlaceholder: "What’s your name?",
  email: "Email address",
  emailPlaceholder: "you@email.com",
  interest: "I’m interested in",
  interests: [
    "Discovering Melcon Paradise",
    "My first property",
    "A second residence",
    "Exploring an investment",
  ],
  message: "Tell me a little more",
  messagePlaceholder: "What you’re looking for, your timeline, your questions…",
  consent:
    "I understand that a summary of my inquiry will be prepared on this device.",
  prepare: "Prepare my inquiry",
  prepared: "Your inquiry is ready",
  preparedText:
    "Download or copy your summary. It has not been sent to Andris yet.",
  noContact:
    "Direct contact will be available once official contact details are confirmed.",
  copy: "Copy inquiry",
  copied: "Copied",
  download: "Download inquiry",
  sendEmail: "Continue by email",
  sendWhatsApp: "Continue on WhatsApp",
  privacy: "Privacy",
  privacyText:
    "Your details are only used to prepare this inquiry in your browser. They are not sent to or stored on a server. Continuing by email or WhatsApp opens your chosen service so you can review the message before sending it. The map connects to OpenStreetMap only when opened. The app stores language, appearance and favorites on this device; reset them in Settings.",
  independent: "Independent portfolio of Andris Peña.",
  footerNote: "Every great story starts with a place.",
  rights: "All rights reserved.",
  settings: "Settings",
  appearance: "Appearance",
  light: "Light",
  dark: "Dark",
  system: "System",
  language: "Language",
  install: "Install app",
  installText: "Take your next plans with you.",
  installHelp:
    "On iPhone: Share → Add to Home Screen. In other browsers: open the menu and look for Install app. Requires HTTPS or localhost.",
  installed: "The app is already installed.",
  offline:
    "You’re offline. Saved content remains available; maps and contact need internet.",
  clearPreferences: "Reset preferences",
  close: "Close",
  back: "Back",
  previous: "Previous image",
  next: "Next image",
  saved: "Project saved",
  save: "Save project",
  removeSaved: "Remove from saved",
  savedEmpty: "You haven’t saved any projects yet.",
  favorites: "Saved",
  skip: "Skip to content",
  notFound: "This place isn’t here yet.",
  notFoundText: "Return to the portfolio to explore the available project.",
  home: "Back to home",
  themeToggle: "Change appearance",
  share: "Share project",
  shared: "Link copied",
  preparing: "Preparing",
  noPhoto: "This image could not be loaded.",
  retry: "Retry",
  view: "View project",
};
const fr: Copy = {
  role: "Conseiller immobilier",
  location: "Punta Cana, République dominicaine",
  portfolio: "Portfolio immobilier",
  nav: ["Accueil", "Projets", "À propos", "Votre investissement", "Parlons-en"],
  tagline: "Votre prochain chapitre,",
  taglineItalic: "au bon endroit.",
  heroKicker: "DES PERSONNES. DES LIEUX. DE NOUVEAUX DÉPARTS.",
  heroLeft: "Un lieu pour vivre.\nUn choix pour grandir.",
  heroRight:
    "Je vous accompagne pour découvrir un bien en accord avec vos projets d’avenir.",
  explore: "Explorer les projets",
  meet: "Rencontrer Andris",
  scroll: "Défiler pour découvrir",
  personal: "Conseil personnel",
  sidebarText: "Les grandes décisions commencent par une bonne conversation.",
  talk: "Parlons-en",
  selection: "01 / DES ESPACES QUI ONT DU SENS",
  projectsTitle: "Imaginez votre vie",
  projectsItalic: "ici.",
  projectsIntro:
    "Un regard sur les espaces, les détails et les possibilités de votre prochain chez-vous.",
  featured: "PROJET À DÉCOUVRIR",
  viewProject: "Découvrir le projet",
  renders: "Vues de synthèse du projet · Images illustratives",
  bedrooms: "Chambres",
  area: "Surface",
  green: "Espaces verts",
  detail: "Les détails font la différence.",
  gallery: "Explorer la galerie",
  galleryTitle: "Un aperçu de votre prochain espace.",
  allPhotos: "Voir toutes les images",
  facets: [
    "La nature au quotidien",
    "Du temps pour vous",
    "Des espaces à partager",
  ],
  facetTags: ["SUMMER GARDENS", "ESPRIT RESORT", "INTÉRIEURS"],
  amenities: "Tout ce qui fait un foyer",
  consultAvailability: "Vérifier la disponibilité",
  availabilityNote: "Prix, disponibilité, conditions et livraison à confirmer.",
  mapLabel: "LE LIEU COMPTE",
  mapTitle: "Votre point de départ,",
  mapItalic: "Vista Cana.",
  mapDescription:
    "Un cadre résidentiel à Punta Cana avec des lacs, des sentiers, un golf et des espaces pour profiter du plein air.",
  openMap: "Ouvrir la localisation",
  loadMap: "Explorer la carte interactive",
  mapPrivacy: "L’ouverture de la carte établit une connexion à OpenStreetMap.",
  mapUnavailable:
    "La carte est indisponible hors ligne. Enregistrez le lieu pour l’ouvrir plus tard.",
  mapPin: "Localisation du projet",
  aboutLabel: "02 / DERRIÈRE CHAQUE DÉCISION",
  aboutTitle: "Bien plus qu’un bien.",
  aboutItalic: "Votre prochain chapitre.",
  aboutText:
    "Je suis Andris Peña, conseiller immobilier. Cet espace vous invite à découvrir des projets à Punta Cana et à parler de vos attentes, avec des informations claires et une attention personnelle.",
  aboutQuote:
    "D’abord, ce qui compte pour vous. Ensuite, le lieu qui le rend possible.",
  aboutCTA: "Parlons de vos projets",
  processLabel: "UN CHEMIN, ENSEMBLE",
  processTitle: "De « je m’y vois »",
  processItalic: "à la prochaine étape.",
  steps: [
    {
      title: "Je vous écoute",
      text: "Un foyer, une résidence secondaire ou un investissement ? Commençons par vos priorités.",
    },
    {
      title: "Nous explorons",
      text: "Découvrez le projet, ses espaces et les informations utiles pour comparer.",
    },
    {
      title: "Nous faisons les comptes",
      text: "Construisons un scénario de paiement et préparons les bonnes questions.",
    },
    {
      title: "Nous avançons",
      text: "Préparez votre demande pour confirmer la disponibilité, les conditions et une éventuelle visite.",
    },
  ],
  calcLabel: "03 / DONNEZ FORME À VOS PROJETS",
  calcTitle: "Votre investissement,",
  calcItalic: "étape par étape.",
  calcIntro:
    "Visualisez la répartition de vos paiements. Ajustez les chiffres à votre propre scénario.",
  calcBadge: "SIMULATEUR DE PAIEMENT",
  propertyValue: "Valeur du bien",
  currency: "Dollars américains (USD)",
  months: "Mois de construction",
  signing: "À la signature",
  construction: "Pendant la construction",
  delivery: "À la livraison",
  monthly: "Mensualité estimée",
  monthsUnit: "mois",
  calcNote:
    "Exercice illustratif, sans valeur d’offre ni de calcul hypothécaire. Réservation, frais, impôts et financement non inclus. Le plan 10 / 40 / 50 fourni reste à confirmer, ainsi que l’imputation de la réservation.",
  calcError:
    "Saisissez une valeur supérieure à 0, entre 1 et 120 mois et des pourcentages totalisant au maximum 100 %.",
  lastPayment: "Dernière mensualité ajustée pour l’arrondi",
  reset: "Réinitialiser",
  downloadPlan: "Télécharger mon scénario",
  guideLabel: "CHOISIR EN CONNAISSANCE DE CAUSE",
  guideTitle: "De bonnes questions.",
  guideItalic: "De meilleurs choix.",
  faqs: [
    {
      q: "Par où commencer pour investir ?",
      a: "Définissez l’usage du bien, votre budget total et votre horizon. Rassemblez ensuite la fiche du projet, les conditions de paiement et les questions à aborder avec votre conseiller.",
    },
    {
      q: "Que signifie un plan 10 / 40 / 50 ?",
      a: "Il répartit la valeur du bien : 10 % à la signature, 40 % pendant la construction et 50 % à la livraison. Les dates, échéances et l’imputation de la réservation doivent être confirmées dans l’offre et le contrat de chaque unité.",
    },
    {
      q: "Que vérifier avant de réserver ?",
      a: "La disponibilité, le prix actuel, l’emplacement, la date de livraison, les spécifications, les frais supplémentaires et les conditions de remboursement. Demandez les documents du projet et faites-les examiner par des professionnels indépendants.",
    },
    {
      q: "Puis-je préparer un achat depuis l’étranger ?",
      a: "Vous pouvez commencer par définir vos objectifs et consulter les documents à distance. Renseignez-vous sur les documents, vérifications et démarches en personne ou par représentation nécessaires dans votre cas.",
    },
  ],
  contactLabel: "VOTRE PROCHAIN CHAPITRE COMMENCE ICI",
  contactTitle: "Dites-moi ce que",
  contactItalic: "vous imaginez.",
  contactIntro:
    "Un foyer pour vous. Un lieu pour se ressourcer. Un projet pour l’avenir. Commençons par votre idée.",
  name: "Votre nom",
  namePlaceholder: "Comment vous appelez-vous ?",
  email: "Adresse e-mail",
  emailPlaceholder: "vous@email.com",
  interest: "Je m’intéresse à",
  interests: [
    "Découvrir Melcon Paradise",
    "Mon premier bien",
    "Une résidence secondaire",
    "Explorer un investissement",
  ],
  message: "Dites-m’en un peu plus",
  messagePlaceholder: "Vos attentes, votre calendrier, vos questions…",
  consent:
    "Je comprends qu’un résumé de ma demande sera préparé sur cet appareil.",
  prepare: "Préparer ma demande",
  prepared: "Votre demande est prête",
  preparedText:
    "Téléchargez ou copiez votre résumé. Il n’a pas encore été envoyé à Andris.",
  noContact:
    "Le contact direct sera disponible après confirmation des coordonnées officielles.",
  copy: "Copier la demande",
  copied: "Copié",
  download: "Télécharger la demande",
  sendEmail: "Continuer par e-mail",
  sendWhatsApp: "Continuer sur WhatsApp",
  privacy: "Confidentialité",
  privacyText:
    "Vos données servent uniquement à préparer cette demande dans votre navigateur. Elles ne sont ni envoyées ni enregistrées sur un serveur. Le passage à l’e-mail ou à WhatsApp ouvre le service choisi pour relire le message avant de l’envoyer. La carte se connecte à OpenStreetMap uniquement à l’ouverture. L’application conserve langue, apparence et favoris sur cet appareil ; vous pouvez les réinitialiser dans les réglages.",
  independent: "Portfolio indépendant d’Andris Peña.",
  footerNote: "Chaque belle histoire commence par un lieu.",
  rights: "Tous droits réservés.",
  settings: "Réglages",
  appearance: "Apparence",
  light: "Clair",
  dark: "Sombre",
  system: "Système",
  language: "Langue",
  install: "Installer l’application",
  installText: "Emportez vos projets avec vous.",
  installHelp:
    "Sur iPhone : Partager → Sur l’écran d’accueil. Dans les autres navigateurs, ouvrez le menu et cherchez Installer l’application. HTTPS ou localhost requis.",
  installed: "L’application est déjà installée.",
  offline:
    "Vous êtes hors ligne. Le contenu enregistré reste disponible ; carte et contact nécessitent internet.",
  clearPreferences: "Réinitialiser les préférences",
  close: "Fermer",
  back: "Retour",
  previous: "Image précédente",
  next: "Image suivante",
  saved: "Projet enregistré",
  save: "Enregistrer le projet",
  removeSaved: "Retirer des favoris",
  savedEmpty: "Vous n’avez pas encore enregistré de projet.",
  favorites: "Favoris",
  skip: "Aller au contenu",
  notFound: "Ce lieu n’est pas encore ici.",
  notFoundText: "Revenez au portfolio pour explorer le projet disponible.",
  home: "Retour à l’accueil",
  themeToggle: "Changer l’apparence",
  share: "Partager le projet",
  shared: "Lien copié",
  preparing: "Préparation",
  noPhoto: "Cette image n’a pas pu être chargée.",
  retry: "Réessayer",
  view: "Voir le projet",
};
export const dictionaries = { es, en, fr };
export type { Copy };
export const localeTags: Record<Locale, string> = {
  es: "es-DO",
  en: "en-US",
  fr: "fr-FR",
};
