export const journeyCopy = {
  es: {
    projects: "Un lugar que va contigo.", projectsIntro: "Recorre los espacios, descubre su ubicación y encuentra el proyecto sobre el que te gustaría conversar.",
    all: "Todos los proyectos", map: "Explorar el mapa", select: "Elige un proyecto", previous: "Proyecto anterior", next: "Proyecto siguiente", render: "Render del proyecto", photos: "Explorar imágenes", selected: "Proyecto seleccionado",
    mapTitle: "Mira el lugar. Imagina tu vida.", mapIntro: "Ubica cada proyecto en Punta Cana. Selecciona un punto para ver sus imágenes, conocer el entorno y abrir su ficha.", activate: "Activar mapa interactivo", loading: "Cargando el mapa…", list: "Lista", mapView: "Mapa", gallery: "Galería", details: "Conocer el proyecto", consult: "Consultar este proyecto", pending: "Conversemos sobre los detalles de este proyecto.",
    about: "Tu próximo paso, acompañado.", aboutText: "Soy Andris Peña, asesor inmobiliario. Te ayudo a explorar opciones en Punta Cana y a poner tus prioridades en el centro de la conversación.", aboutAction: "Conoce cómo te acompaño", calculator: "Ponle números a tu próximo paso.", calculatorText: "Explora un escenario de pagos a tu ritmo, ajusta los importes y prepara tus preguntas.", calculatorAction: "Abrir calculadora", contact: "Todo empieza con una conversación.", contactText: "Cuéntame qué estás buscando. Juntos podemos dar forma al siguiente paso.", contactAction: "Hablemos", back: "Volver a proyectos", contactPage: "Conversemos", aboutPage: "Sobre Andris", investmentPage: "Calculadora de pagos", overview: "Explorar", viewAll: "Ver todos", saved: "Guardados", noSaved: "Aún no has guardado proyectos.", saveHint: "Toca el corazón de un proyecto para volver a él después.", filter: "Más filtros", noMatch: "No hay proyectos que coincidan.", projectField: "Proyecto de interés", general: "Asesoría general", mapHelp: "Arrastra para explorar. Usa + y − para acercarte.",
  },
  en: {
    projects: "A place that feels like you.", projectsIntro: "Explore the spaces, discover their location and find the project you would like to talk about.",
    all: "All projects", map: "Explore the map", select: "Choose a project", previous: "Previous project", next: "Next project", render: "Project rendering", photos: "Explore images", selected: "Selected project",
    mapTitle: "See the place. Picture your life.", mapIntro: "Locate each project in Punta Cana. Select a pin to see its images, explore the area and open its profile.", activate: "Activate interactive map", loading: "Loading the map…", list: "List", mapView: "Map", gallery: "Gallery", details: "Discover the project", consult: "Ask about this project", pending: "Let’s talk about this project’s details.",
    about: "Your next step, with guidance.", aboutText: "I’m Andris Peña, a real estate advisor. I help you explore options in Punta Cana and keep your priorities at the centre of the conversation.", aboutAction: "Discover how I can help", calculator: "Put numbers to your next step.", calculatorText: "Explore a payment scenario at your own pace, adjust the amounts and prepare your questions.", calculatorAction: "Open calculator", contact: "It starts with a conversation.", contactText: "Tell me what you are looking for. Together, we can shape the next step.", contactAction: "Let’s talk", back: "Back to projects", contactPage: "Let’s talk", aboutPage: "About Andris", investmentPage: "Payment calculator", overview: "Explore", viewAll: "View all", saved: "Saved", noSaved: "You haven’t saved any projects yet.", saveHint: "Tap a project’s heart to come back to it later.", filter: "More filters", noMatch: "No projects match your search.", projectField: "Project of interest", general: "General advice", mapHelp: "Drag to explore. Use + and − to zoom.",
  },
  fr: {
    projects: "Un lieu qui vous ressemble.", projectsIntro: "Explorez les espaces, découvrez leur emplacement et trouvez le projet dont vous aimeriez parler.",
    all: "Tous les projets", map: "Explorer la carte", select: "Choisir un projet", previous: "Projet précédent", next: "Projet suivant", render: "Vue de synthèse", photos: "Explorer les images", selected: "Projet sélectionné",
    mapTitle: "Découvrez le lieu. Imaginez votre vie.", mapIntro: "Situez chaque projet à Punta Cana. Sélectionnez un point pour découvrir ses images, son environnement et sa fiche.", activate: "Activer la carte interactive", loading: "Chargement de la carte…", list: "Liste", mapView: "Carte", gallery: "Galerie", details: "Découvrir le projet", consult: "Se renseigner sur ce projet", pending: "Parlons des détails de ce projet.",
    about: "Votre prochain pas, accompagné.", aboutText: "Je suis Andris Peña, conseiller immobilier. Je vous aide à explorer les options à Punta Cana en plaçant vos priorités au centre de la conversation.", aboutAction: "Découvrir mon accompagnement", calculator: "Chiffrez votre prochaine étape.", calculatorText: "Explorez un scénario de paiement à votre rythme, ajustez les montants et préparez vos questions.", calculatorAction: "Ouvrir le simulateur", contact: "Tout commence par une conversation.", contactText: "Dites-moi ce que vous recherchez. Ensemble, préparons la prochaine étape.", contactAction: "Parlons-en", back: "Retour aux projets", contactPage: "Parlons-en", aboutPage: "À propos d’Andris", investmentPage: "Simulateur de paiement", overview: "Explorer", viewAll: "Voir tous", saved: "Favoris", noSaved: "Vous n’avez pas encore enregistré de projet.", saveHint: "Touchez le cœur d’un projet pour le retrouver plus tard.", filter: "Plus de filtres", noMatch: "Aucun projet ne correspond.", projectField: "Projet souhaité", general: "Conseil général", mapHelp: "Faites glisser pour explorer. Utilisez + et − pour zoomer.",
  },
} as const;
