/**
 * Textos de la pagina de mapa.
 * Las coordenadas provienen de los enlaces que entrego el cliente y estan
 * contrastadas en docs/design/project-location-evidence.json.
 */
export const mapExplorerCopy = {
  es: {
    title: "Dónde están",
    intro: "Tres ubicaciones en Punta Cana, tomadas del enlace de mapa de cada proyecto.",
    listLabel: "Proyectos en el mapa",
    overview: "Vista general",
    overviewHint: "Ver todas las ubicaciones",
    select: (name: string) => `Centrar el mapa en ${name}`,
    open: "Ver el proyecto",
    googleMaps: "Google Maps",
    style: "Estilo del mapa",
    detailed: "Mapa detallado",
    muted: "Mapa sobrio",
    satelliteView: "Vista satelital",
    streetView: "Volver al mapa",
    satelliteTone: "Tratamiento de imagen",
    natural: "Natural",
    vivid: "Vivo",
    nocturne: "Nocturno",
    puntaCanaOnly: "Exploración limitada a Punta Cana",
    enable3d: "Activar vista 3D",
    disable3d: "Desactivar vista 3D",
    threeD: "Vista 3D",
    flat: "Vista plana",
    zoomIn: "Acercar",
    zoomOut: "Alejar",
    reset: "Ver los tres proyectos",
    retry: "Reintentar",
    error: "El mapa no se pudo cargar.",
    offline: "Sin conexión no se puede cargar el mapa.",
    privacy: "OpenFreeMap y OpenStreetMap. La vista satelital usa imágenes de Esri con atribución.",
  },
  en: {
    title: "Where they are",
    intro: "Three locations in Punta Cana, taken from each project's map link.",
    listLabel: "Projects on the map",
    overview: "Overview",
    overviewHint: "See every location",
    select: (name: string) => `Centre the map on ${name}`,
    open: "View the project",
    googleMaps: "Google Maps",
    style: "Map style",
    detailed: "Detailed map",
    muted: "Muted map",
    satelliteView: "Satellite view",
    streetView: "Back to map",
    satelliteTone: "Image treatment",
    natural: "Natural",
    vivid: "Vivid",
    nocturne: "Nocturne",
    puntaCanaOnly: "Exploration limited to Punta Cana",
    enable3d: "Enable 3D view",
    disable3d: "Disable 3D view",
    threeD: "3D view",
    flat: "Flat view",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    reset: "See all three projects",
    retry: "Try again",
    error: "The map could not load.",
    offline: "The map cannot load while you are offline.",
    privacy: "Powered by OpenFreeMap and OpenStreetMap. Satellite imagery by Esri with attribution.",
  },
  fr: {
    title: "Où ils se trouvent",
    intro: "Trois emplacements à Punta Cana, issus du lien de carte de chaque projet.",
    listLabel: "Projets sur la carte",
    overview: "Vue d’ensemble",
    overviewHint: "Voir tous les emplacements",
    select: (name: string) => `Centrer la carte sur ${name}`,
    open: "Voir le projet",
    googleMaps: "Google Maps",
    style: "Style de la carte",
    detailed: "Carte détaillée",
    muted: "Carte sobre",
    satelliteView: "Vue satellite",
    streetView: "Retour à la carte",
    satelliteTone: "Traitement de l’image",
    natural: "Naturel",
    vivid: "Vif",
    nocturne: "Nocturne",
    puntaCanaOnly: "Exploration limitée à Punta Cana",
    enable3d: "Activer la vue 3D",
    disable3d: "Désactiver la vue 3D",
    threeD: "Vue 3D",
    flat: "Vue plane",
    zoomIn: "Zoomer",
    zoomOut: "Dézoomer",
    reset: "Voir les trois projets",
    retry: "Réessayer",
    error: "La carte n'a pas pu se charger.",
    offline: "Impossible de charger la carte hors connexion.",
    privacy: "Basé sur OpenFreeMap et OpenStreetMap. Imagerie satellite Esri avec attribution.",
  },
} as const;
