/**
 * Textos de la pagina de mapa.
 * Las coordenadas provienen de los enlaces que entrego el cliente y estan
 * contrastadas en docs/design/project-location-evidence.json.
 */
export const mapExplorerCopy = {
  es: {
    title: "Dónde están",
    intro: "Tres ubicaciones en Punta Cana, tomadas del enlace de mapa de cada proyecto.",
    listLabel: "Proyectos en el mapa",
    select: (name: string) => `Centrar el mapa en ${name}`,
    open: "Ver el proyecto",
    googleMaps: "Google Maps",
    style: "Estilo del mapa",
    detailed: "Mapa detallado",
    muted: "Mapa sobrio",
    zoomIn: "Acercar",
    zoomOut: "Alejar",
    reset: "Ver los tres proyectos",
    retry: "Reintentar",
    error: "El mapa no se pudo cargar.",
    offline: "Sin conexión no se puede cargar el mapa.",
    privacy: "El mapa se conecta con OpenStreetMap.",
  },
  en: {
    title: "Where they are",
    intro: "Three locations in Punta Cana, taken from each project's map link.",
    listLabel: "Projects on the map",
    select: (name: string) => `Centre the map on ${name}`,
    open: "View the project",
    googleMaps: "Google Maps",
    style: "Map style",
    detailed: "Detailed map",
    muted: "Muted map",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    reset: "See all three projects",
    retry: "Try again",
    error: "The map could not load.",
    offline: "The map cannot load while you are offline.",
    privacy: "The map connects to OpenStreetMap.",
  },
  fr: {
    title: "Où ils se trouvent",
    intro: "Trois emplacements à Punta Cana, issus du lien de carte de chaque projet.",
    listLabel: "Projets sur la carte",
    select: (name: string) => `Centrer la carte sur ${name}`,
    open: "Voir le projet",
    googleMaps: "Google Maps",
    style: "Style de la carte",
    detailed: "Carte détaillée",
    muted: "Carte sobre",
    zoomIn: "Zoomer",
    zoomOut: "Dézoomer",
    reset: "Voir les trois projets",
    retry: "Réessayer",
    error: "La carte n'a pas pu se charger.",
    offline: "Impossible de charger la carte hors connexion.",
    privacy: "La carte se connecte à OpenStreetMap.",
  },
} as const;
